import * as XLSX from 'xlsx';

interface ExcelColumnConfig {
  header: string;
  key: string;
  width?: number;
  type?: 'string' | 'number' | 'date' | 'currency';
}

interface ExcelExportOptions {
  sheetName: string;
  columns: ExcelColumnConfig[];
  data: any[];
  title?: string;
  includeMetadata?: boolean;
  generatedBy?: string;
}

export class ExcelExporter {
  /**
   * Create formatted Excel workbook with styling
   */
  static createWorkbook(options: ExcelExportOptions): XLSX.WorkBook {
    const { sheetName, columns, data, title, includeMetadata, generatedBy } = options;
    
    const workbook = XLSX.utils.book_new();
    const worksheetData: any[][] = [];

    let currentRow = 0;

    // Add title if provided
    if (title) {
      worksheetData.push([title]);
      worksheetData.push([]);
      currentRow = 2;
    }

    // Add metadata
    if (includeMetadata) {
      worksheetData.push(['Generated Date:', new Date().toLocaleDateString()]);
      if (generatedBy) {
        worksheetData.push(['Generated By:', generatedBy]);
      }
      worksheetData.push([]);
      currentRow += includeMetadata ? 3 : 0;
    }

    // Add headers
    const headers = columns.map(col => col.header);
    worksheetData.push(headers);

    // Add data rows
    data.forEach(row => {
      const rowData = columns.map(col => {
        const value = row[col.key];
        return this.formatCellValue(value, col.type);
      });
      worksheetData.push(rowData);
    });

    // Create worksheet
    const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

    // Set column widths
    const columnWidths = columns.map(col => ({
      wch: col.width || this.calculateColumnWidth(col.header, data, col.key)
    }));
    worksheet['!cols'] = columnWidths;

    // Apply cell formatting
    this.applyCellFormatting(worksheet, columns, currentRow, data.length);

    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    
    return workbook;
  }

  /**
   * Create workbook with multiple sheets
   */
  static createMultiSheetWorkbook(sheets: ExcelExportOptions[]): XLSX.WorkBook {
    const workbook = XLSX.utils.book_new();

    sheets.forEach(sheetOptions => {
      const { sheetName, columns, data, title, includeMetadata, generatedBy } = sheetOptions;
      const worksheetData: any[][] = [];

      let currentRow = 0;

      if (title) {
        worksheetData.push([title]);
        worksheetData.push([]);
        currentRow = 2;
      }

      if (includeMetadata) {
        worksheetData.push(['Generated Date:', new Date().toLocaleDateString()]);
        if (generatedBy) {
          worksheetData.push(['Generated By:', generatedBy]);
        }
        worksheetData.push([]);
        currentRow += 3;
      }

      const headers = columns.map(col => col.header);
      worksheetData.push(headers);

      data.forEach(row => {
        const rowData = columns.map(col => {
          const value = row[col.key];
          return this.formatCellValue(value, col.type);
        });
        worksheetData.push(rowData);
      });

      const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

      const columnWidths = columns.map(col => ({
        wch: col.width || this.calculateColumnWidth(col.header, data, col.key)
      }));
      worksheet['!cols'] = columnWidths;

      this.applyCellFormatting(worksheet, columns, currentRow, data.length);

      XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    });

    return workbook;
  }

  /**
   * Format cell value based on type
   */
  private static formatCellValue(value: any, type?: string): any {
    if (value === null || value === undefined) return '';

    switch (type) {
      case 'date':
        return value instanceof Date ? value : new Date(value);
      case 'number':
        return typeof value === 'number' ? value : parseFloat(value) || 0;
      case 'currency':
        return typeof value === 'number' ? value : parseFloat(value) || 0;
      case 'string':
      default:
        return String(value);
    }
  }

  /**
   * Calculate optimal column width
   */
  private static calculateColumnWidth(header: string, data: any[], key: string): number {
    const headerLength = header.length;
    const maxDataLength = data.reduce((max, row) => {
      const value = String(row[key] || '');
      return Math.max(max, value.length);
    }, 0);

    return Math.min(Math.max(headerLength, maxDataLength) + 2, 50);
  }

  /**
   * Apply cell formatting (bold headers, number formats, etc.)
   */
  private static applyCellFormatting(
    worksheet: XLSX.WorkSheet,
    columns: ExcelColumnConfig[],
    headerRow: number,
    dataRowCount: number
  ): void {
    const range = XLSX.utils.decode_range(worksheet['!ref'] || 'A1');

    // Format header row
    for (let col = range.s.c; col <= range.e.c; col++) {
      const cellAddress = XLSX.utils.encode_cell({ r: headerRow, c: col });
      if (!worksheet[cellAddress]) continue;
      
      worksheet[cellAddress].s = {
        font: { bold: true },
        fill: { fgColor: { rgb: "CCCCCC" } },
        alignment: { horizontal: "center", vertical: "center" }
      };
    }

    // Format data cells based on column type
    for (let row = headerRow + 1; row <= headerRow + dataRowCount; row++) {
      columns.forEach((col, colIndex) => {
        const cellAddress = XLSX.utils.encode_cell({ r: row, c: colIndex });
        if (!worksheet[cellAddress]) return;

        switch (col.type) {
          case 'currency':
            worksheet[cellAddress].z = '$#,##0.00';
            break;
          case 'number':
            worksheet[cellAddress].z = '#,##0.00';
            break;
          case 'date':
            worksheet[cellAddress].z = 'yyyy-mm-dd';
            break;
        }
      });
    }
  }

  /**
   * Export simple data array to Excel
   */
  static exportSimple(
    data: any[],
    fileName: string,
    sheetName: string = 'Sheet1'
  ): void {
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    XLSX.writeFile(workbook, fileName);
  }

  /**
   * Download workbook
   */
  static downloadWorkbook(workbook: XLSX.WorkBook, fileName: string): void {
    XLSX.writeFile(workbook, fileName);
  }
}

// Example usage in your ReportContext
export const exportEngineerSummaryExample = (data: any[], userName: string) => {
  const columns: ExcelColumnConfig[] = [
    { header: 'Engineer Name', key: 'engineerName', width: 20 },
    { header: 'Project', key: 'project', width: 25 },
    { header: 'Tasks Completed', key: 'tasksCompleted', type: 'number', width: 15 },
    { header: 'Hours Logged', key: 'hoursLogged', type: 'number', width: 15 },
    { header: 'Efficiency %', key: 'efficiency', type: 'number', width: 12 },
    { header: 'Total Cost', key: 'totalCost', type: 'currency', width: 15 },
    { header: 'Last Updated', key: 'lastUpdated', type: 'date', width: 15 },
  ];

  const workbook = ExcelExporter.createWorkbook({
    sheetName: 'Engineer Summary',
    columns,
    data,
    title: 'SitePilot - Engineer Summary Report',
    includeMetadata: true,
    generatedBy: userName,
  });

  return workbook;
};

// Example for multiple sheets
export const exportAllReportsExample = (
  summaryData: any[],
  performanceData: any[],
  claimsData: any[],
  userName: string
) => {
  const sheets: ExcelExportOptions[] = [
    {
      sheetName: 'Engineer Summary',
      columns: [
        { header: 'Engineer', key: 'engineerName', width: 20 },
        { header: 'Tasks', key: 'tasksCompleted', type: 'number' },
        { header: 'Hours', key: 'hoursLogged', type: 'number' },
      ],
      data: summaryData,
      title: 'Engineer Summary',
      includeMetadata: true,
      generatedBy: userName,
    },
    {
      sheetName: 'Performance',
      columns: [
        { header: 'Engineer', key: 'engineerName', width: 20 },
        { header: 'Performance Score', key: 'score', type: 'number' },
        { header: 'Rating', key: 'rating' },
      ],
      data: performanceData,
      title: 'Performance Report',
      includeMetadata: true,
      generatedBy: userName,
    },
    {
      sheetName: 'Claims',
      columns: [
        { header: 'Claim ID', key: 'claimId' },
        { header: 'Amount', key: 'amount', type: 'currency' },
        { header: 'Status', key: 'status' },
        { header: 'Date', key: 'date', type: 'date' },
      ],
      data: claimsData,
      title: 'Detailed Claims',
      includeMetadata: true,
      generatedBy: userName,
    },
  ];

  return ExcelExporter.createMultiSheetWorkbook(sheets);
};