// File: lib/pdf-export-helper.ts
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, parseISO } from 'date-fns';

interface PerformanceData {
  id: string;
  "engineer Name": string;
  "avatarUrl"?: string;
  "projects": any[];
  "tasks": any[];
  "claims": any[];
}

interface ExportOptions {
  companyName?: string;
  userName?: string;
  dateRange?: { from?: Date; to?: Date };
}

export const exportEngineerPerformanceToPDF = (
  performanceData: PerformanceData[],
  options: ExportOptions = {}
): Blob => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const { companyName = 'SitePilot', userName = 'N/A', dateRange } = options;
  
  let yPosition = 15;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;

  // Helper to add header on each page
  const addHeader = (isFirstPage = false) => {
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(companyName, margin, 10);
    doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy')}`, pageWidth - margin, 10, { align: 'right' });
    
    if (isFirstPage) {
      yPosition = 20;
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text('Engineer Performance Report', margin, yPosition);
      yPosition += 8;
      
      // Metadata
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(`Generated by: ${userName}`, margin, yPosition);
      
      if (dateRange?.from || dateRange?.to) {
        const dateRangeStr = `Date Range: ${dateRange?.from ? format(dateRange.from, 'MMM dd, yyyy') : 'N/A'} - ${dateRange?.to ? format(dateRange.to, 'MMM dd, yyyy') : 'N/A'}`;
        yPosition += 5;
        doc.text(dateRangeStr, margin, yPosition);
      }
      
      yPosition += 10;
      // Draw separator line
      doc.setDrawColor(200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;
    } else {
      yPosition = 20;
    }
  };

  // Add header for first page
  addHeader(true);

  // Process each engineer
  performanceData.forEach((engineer, engineerIndex) => {
    const engineerName = engineer["engineer Name"];
    
    // Check if we need a new page for this engineer
    if (engineerIndex > 0) {
      doc.addPage();
      addHeader(false);
    }

    // Engineer Name Header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(engineerName, margin, yPosition);
    yPosition += 6; // ✅ Increased spacing from 3 to 6
    
    // Summary badges
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Projects: ${engineer.projects.length} | Tasks: ${engineer.tasks.length} | Claims: ${engineer.claims.length}`, margin, yPosition);
    yPosition += 10; // ✅ Increased spacing from 8 to 10

    // Projects Table
    if (engineer.projects.length > 0) {
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text('Assigned Projects', margin, yPosition);
      yPosition += 2;

      autoTable(doc, {
        startY: yPosition,
        head: [['Project Name', 'Status', 'End Date']],
        body: engineer.projects.map(p => [
          p.name,
          p.status,
          format(parseISO(p.endDate), 'MMM dd, yyyy')
        ]),
        theme: 'striped',
        headStyles: {
          fillColor: [71, 85, 105],
          fontSize: 9,
          fontStyle: 'bold',
        },
        bodyStyles: {
          fontSize: 8,
        },
        columnStyles: {
          0: { cellWidth: 'auto' }, // Auto width
          1: { cellWidth: 'auto' },
          2: { cellWidth: 'auto' },
        },
        tableWidth: 'auto', // Auto-fit to page width
        margin: { left: margin, right: margin },
      });

      yPosition = (doc as any).lastAutoTable.finalY + 10;
    } else {
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('No projects assigned', margin + 5, yPosition);
      yPosition += 10;
    }

    // Check if we need a new page
    if (yPosition > 240) {
      doc.addPage();
      addHeader(false);
    }

    // Tasks Table
    if (engineer.tasks.length > 0) {
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text('Assigned Tasks', margin, yPosition);
      yPosition += 2;

      autoTable(doc, {
        startY: yPosition,
        head: [['Task Title', 'Project', 'Role', 'Due Date', 'Status']],
        body: engineer.tasks.map(t => [
          t.title,
          t.projectName || 'N/A',
          t.owner === engineer.id ? 'Owner' : 'Contributor',
          format(parseISO(t.dueDate), 'MMM dd, yyyy'),
          t.status
        ]),
        theme: 'striped',
        headStyles: {
          fillColor: [71, 85, 105],
          fontSize: 9,
          fontStyle: 'bold',
        },
        bodyStyles: {
          fontSize: 8,
        },
        columnStyles: {
          0: { cellWidth: 55 },
          1: { cellWidth: 45 },
          2: { cellWidth: 25 },
          3: { cellWidth: 30 },
          4: { cellWidth: 27 },
        },
        margin: { left: margin, right: margin },
      });

      yPosition = (doc as any).lastAutoTable.finalY + 10;
    } else {
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('No tasks assigned', margin + 5, yPosition);
      yPosition += 10;
    }

    // Check if we need a new page
    if (yPosition > 240) {
      doc.addPage();
      addHeader(false);
    }

    // Claims Table
    if (engineer.claims.length > 0) {
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text('Submitted Claims', margin, yPosition);
      yPosition += 2;

      autoTable(doc, {
        startY: yPosition,
        head: [['Claim Title', 'Project', 'Amount', 'Status']],
        body: engineer.claims.map(c => [
          c.title,
          c.projectName || 'N/A',
          `${c.currency} ${c.amount.toLocaleString()}`,
          c.status
        ]),
        theme: 'striped',
        headStyles: {
          fillColor: [71, 85, 105],
          fontSize: 9,
          fontStyle: 'bold',
        },
        bodyStyles: {
          fontSize: 8,
        },
        columnStyles: {
          0: { cellWidth: 70 },
          1: { cellWidth: 50 },
          2: { cellWidth: 35 },
          3: { cellWidth: 27 },
        },
        margin: { left: margin, right: margin },
      });

      yPosition = (doc as any).lastAutoTable.finalY + 10;
    } else {
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('No claims submitted', margin + 5, yPosition);
      yPosition += 10;
    }
  });

  // Add page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
};

// Preview URL generator
export const createPDFPreviewUrl = (blob: Blob): string => {
  return URL.createObjectURL(blob);
};

// Download PDF
export const downloadPDF = (blob: Blob, fileName: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Engineer Summary Report PDF Export
interface SummaryData {
  "engineer Name": string;
  "Completed Sites": number;
  "Total Amount (RM)": number;
  "Claim (RM)": number;
  "Ongoing Sites": number;
  "Due Sites": number;
}

export const exportEngineerSummaryToPDF = (
  summaryData: SummaryData[],
  options: ExportOptions = {}
): Blob => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const { companyName = 'SitePilot', userName = 'N/A', dateRange } = options;
  
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;
  let yPosition = 15;

  // Add header
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(companyName, margin, 10);
  doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy')}`, pageWidth - margin, 10, { align: 'right' });
  
  yPosition = 20;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Engineer Summary Report', margin, yPosition);
  yPosition += 8;
  
  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Generated by: ${userName}`, margin, yPosition);
  
  if (dateRange?.from || dateRange?.to) {
    const dateRangeStr = `Date Range: ${dateRange?.from ? format(dateRange.from, 'MMM dd, yyyy') : 'N/A'} - ${dateRange?.to ? format(dateRange.to, 'MMM dd, yyyy') : 'N/A'}`;
    yPosition += 5;
    doc.text(dateRangeStr, margin, yPosition);
  }
  
  yPosition += 10;
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Summary Table
  if (summaryData.length > 0) {
    autoTable(doc, {
      startY: yPosition,
      head: [[
        'Engineer Name',
        'Completed Sites',
        'Total Amount (RM)',
        'Claim (RM)',
        'Ongoing Sites',
        'Due Sites'
      ]],
      body: summaryData.map(engineer => [
        engineer["engineer Name"],
        engineer["Completed Sites"].toString(),
        `RM ${engineer["Total Amount (RM)"].toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        `RM ${engineer["Claim (RM)"].toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        engineer["Ongoing Sites"].toString(),
        engineer["Due Sites"].toString()
      ]),
      theme: 'striped',
      headStyles: {
        fillColor: [71, 85, 105],
        fontSize: 9,
        fontStyle: 'bold',
        halign: 'center',
      },
      bodyStyles: {
        fontSize: 9,
      },
      columnStyles: {
        0: { cellWidth: 40, halign: 'left' },
        1: { cellWidth: 25, halign: 'center' },
        2: { cellWidth: 35, halign: 'right' },
        3: { cellWidth: 30, halign: 'right' },
        4: { cellWidth: 25, halign: 'center' },
        5: { cellWidth: 20, halign: 'center' },
      },
      margin: { left: margin, right: margin },
      didDrawCell: (data) => {
        // Highlight due sites in red if > 0
        if (data.column.index === 5 && data.section === 'body') {
          const value = summaryData[data.row.index]["Due Sites"];
          if (value > 0) {
            doc.setTextColor(220, 38, 38); // Red color
          }
        }
      },
      didDrawPage: (data) => {
        // Add page numbers
        const pageCount = doc.getNumberOfPages();
        const currentPage = doc.getCurrentPageInfo().pageNumber;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${currentPage} of ${pageCount}`,
          pageWidth / 2,
          doc.internal.pageSize.height - 10,
          { align: 'center' }
        );
      }
    });

    yPosition = (doc as any).lastAutoTable.finalY + 15;

    // Add summary statistics
    const totalCompleted = summaryData.reduce((sum, e) => sum + e["Completed Sites"], 0);
    const totalOngoing = summaryData.reduce((sum, e) => sum + e["Ongoing Sites"], 0);
    const totalDue = summaryData.reduce((sum, e) => sum + e["Due Sites"], 0);
    const totalAmount = summaryData.reduce((sum, e) => sum + e["Total Amount (RM)"], 0);
    const totalClaims = summaryData.reduce((sum, e) => sum + e["Claim (RM)"], 0);

    // Check if we need a new page for summary
    if (yPosition > 240) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Overall Summary', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60);

    const summaryStats = [
      `Total Engineers: ${summaryData.length}`,
      `Total Completed Sites: ${totalCompleted}`,
      `Total Ongoing Sites: ${totalOngoing}`,
      `Total Due Sites: ${totalDue}`,
      `Total Project Amount: RM ${totalAmount.toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `Total Claims: RM ${totalClaims.toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    ];

    summaryStats.forEach(stat => {
      doc.text(stat, margin + 5, yPosition);
      yPosition += 6;
    });
  } else {
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('No engineer data available for the selected filters.', margin, yPosition);
  }

  // Add page numbers to all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
};

// Add these functions to your lib/pdf-export-helper.ts file

// Detailed Claims Report PDF Export
interface DetailedClaimData {
  "engineer Name": string;
  "Site Name": string;
  "e-Invoice No.": string;
  "Claim Title": string;
  "Amount": number;
  "Currency": string;
  "Date": string;
  "Status": string;
}

export const exportDetailedClaimsToPDF = (
  claimsData: DetailedClaimData[],
  options: ExportOptions = {}
): Blob => {
  const doc = new jsPDF({
    orientation: 'landscape', // ✅ Landscape for wider tables
    unit: 'mm',
    format: 'a4',
  });

  const { companyName = 'SitePilot', userName = 'N/A', dateRange } = options;
  
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;
  let yPosition = 15;

  // Header
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(companyName, margin, 10);
  doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy')}`, pageWidth - margin, 10, { align: 'right' });
  
  yPosition = 20;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Detailed Claims Report', margin, yPosition);
  yPosition += 8;
  
  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Generated by: ${userName}`, margin, yPosition);
  
  if (dateRange?.from || dateRange?.to) {
    const dateRangeStr = `Date Range: ${dateRange?.from ? format(dateRange.from, 'MMM dd, yyyy') : 'N/A'} - ${dateRange?.to ? format(dateRange.to, 'MMM dd, yyyy') : 'N/A'}`;
    yPosition += 5;
    doc.text(dateRangeStr, margin, yPosition);
  }
  
  yPosition += 10;
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Claims Table
  if (claimsData.length > 0) {
    autoTable(doc, {
      startY: yPosition,
      head: [[
        'Engineer',
        'Site Name',
        'e-Invoice No.',
        'Claim Title',
        'Amount',
        'Date',
        'Status'
      ]],
      body: claimsData.map(claim => [
        claim["engineer Name"],
        claim["Site Name"],
        claim["e-Invoice No."],
        claim["Claim Title"],
        `${claim.Currency} ${claim.Amount.toLocaleString('en-MY', { minimumFractionDigits: 2 })}`,
        format(parseISO(claim.Date), 'MMM dd, yyyy'),
        claim.Status
      ]),
      theme: 'striped',
      headStyles: {
        fillColor: [71, 85, 105],
        fontSize: 9,
        fontStyle: 'bold',
        halign: 'center',
      },
      bodyStyles: {
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 'auto' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 'auto' },
        4: { cellWidth: 'auto', halign: 'right' },
        5: { cellWidth: 'auto' },
        6: { cellWidth: 'auto', halign: 'center' },
      },
      tableWidth: 'auto',
      margin: { left: margin, right: margin },
    });

    // Summary
    const totalAmount = claimsData.reduce((sum, c) => sum + c.Amount, 0);
    const paidClaims = claimsData.filter(c => c.Status === 'Paid').length;
    const pendingClaims = claimsData.filter(c => c.Status === 'Pending').length;

    yPosition = (doc as any).lastAutoTable.finalY + 15;

    if (yPosition > 170) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Claims Summary', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Claims: ${claimsData.length}`, margin + 5, yPosition);
    yPosition += 6;
    doc.text(`Paid Claims: ${paidClaims}`, margin + 5, yPosition);
    yPosition += 6;
    doc.text(`Pending Claims: ${pendingClaims}`, margin + 5, yPosition);
    yPosition += 6;
    doc.text(`Total Amount: RM ${totalAmount.toLocaleString('en-MY', { minimumFractionDigits: 2 })}`, margin + 5, yPosition);
  }

  // Page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
};

// Project Status Report PDF Export
interface ProjectStatusData {
  "Project Name": string;
  "Progress": number;
  "Status": string;
  "Work Items": string;
  "Start Date": string;
  "End Date": string;
  "Assigned Engineers": string;
  "Gross Profit": number;
  "Margin Profit (%)": number;
  "Currency": string;
}

export const exportProjectStatusToPDF = (
  projectsData: ProjectStatusData[],
  options: ExportOptions = {}
): Blob => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const { companyName = 'SitePilot', userName = 'N/A', dateRange } = options;
  
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;
  let yPosition = 15;

  // Header
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(companyName, margin, 10);
  doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy')}`, pageWidth - margin, 10, { align: 'right' });
  
  yPosition = 20;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Project Status Report', margin, yPosition);
  yPosition += 8;
  
  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Generated by: ${userName}`, margin, yPosition);
  
  if (dateRange?.from || dateRange?.to) {
    const dateRangeStr = `Date Range: ${dateRange?.from ? format(dateRange.from, 'MMM dd, yyyy') : 'N/A'} - ${dateRange?.to ? format(dateRange.to, 'MMM dd, yyyy') : 'N/A'}`;
    yPosition += 5;
    doc.text(dateRangeStr, margin, yPosition);
  }
  
  yPosition += 10;
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Projects Table
  if (projectsData.length > 0) {
    autoTable(doc, {
      startY: yPosition,
      head: [[
        'Project Name',
        'Progress',
        'Status',
        'Work Items',
        'Start Date',
        'End Date',
        'Engineers',
        'Gross Profit',
        'Margin %'
      ]],
      body: projectsData.map(project => [
        project["Project Name"],
        `${project.Progress}%`,
        project.Status,
        project["Work Items"],
        format(parseISO(project["Start Date"]), 'MMM dd, yy'),
        format(parseISO(project["End Date"]), 'MMM dd, yy'),
        project["Assigned Engineers"],
        `${project.Currency} ${project["Gross Profit"].toLocaleString('en-MY')}`,
        `${project["Margin Profit (%)"].toFixed(1)}%`
      ]),
      theme: 'striped',
      headStyles: {
        fillColor: [71, 85, 105],
        fontSize: 8,
        fontStyle: 'bold',
        halign: 'center',
      },
      bodyStyles: {
        fontSize: 7,
      },
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 18, halign: 'center' },
        2: { cellWidth: 25 },
        3: { cellWidth: 20, halign: 'center' },
        4: { cellWidth: 25 },
        5: { cellWidth: 25 },
        6: { cellWidth: 40 },
        7: { cellWidth: 30, halign: 'right' },
        8: { cellWidth: 18, halign: 'right' },
      },
      margin: { left: margin, right: margin },
    });
  }

  // Page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
};

// Task & Milestone Report PDF Export
interface TaskMilestoneData {
  "Work Item Title": string;
  "Type": 'Task' | 'Milestone';
  "Project Name": string;
  "Owner": string;
  "Due Date": string;
  "Status": string;
}

export const exportTaskMilestoneToPDF = (
  tasksData: TaskMilestoneData[],
  options: ExportOptions = {}
): Blob => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const { companyName = 'SitePilot', userName = 'N/A', dateRange } = options;
  
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;
  let yPosition = 15;

  // Header
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(companyName, margin, 10);
  doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy')}`, pageWidth - margin, 10, { align: 'right' });
  
  yPosition = 20;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Task & Milestone Report', margin, yPosition);
  yPosition += 8;
  
  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Generated by: ${userName}`, margin, yPosition);
  
  if (dateRange?.from || dateRange?.to) {
    const dateRangeStr = `Date Range: ${dateRange?.from ? format(dateRange.from, 'MMM dd, yyyy') : 'N/A'} - ${dateRange?.to ? format(dateRange.to, 'MMM dd, yyyy') : 'N/A'}`;
    yPosition += 5;
    doc.text(dateRangeStr, margin, yPosition);
  }
  
  yPosition += 10;
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Tasks Table
  if (tasksData.length > 0) {
    autoTable(doc, {
      startY: yPosition,
      head: [[
        'Work Item Title',
        'Type',
        'Project',
        'Owner',
        'Due Date',
        'Status'
      ]],
      body: tasksData.map(task => [
        task["Work Item Title"],
        task.Type,
        task["Project Name"],
        task.Owner,
        format(parseISO(task["Due Date"]), 'MMM dd, yyyy'),
        task.Status
      ]),
      theme: 'striped',
      headStyles: {
        fillColor: [71, 85, 105],
        fontSize: 9,
        fontStyle: 'bold',
        halign: 'center',
      },
      bodyStyles: {
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 20, halign: 'center' },
        2: { cellWidth: 40 },
        3: { cellWidth: 30 },
        4: { cellWidth: 25 },
        5: { cellWidth: 20, halign: 'center' },
      },
      margin: { left: margin, right: margin },
    });

    // Summary
    const totalTasks = tasksData.filter(t => t.Type === 'Task').length;
    const totalMilestones = tasksData.filter(t => t.Type === 'Milestone').length;
    const completedItems = tasksData.filter(t => t.Status === 'Completed').length;
    const overdueItems = tasksData.filter(t => t.Status === 'Overdue').length;

    yPosition = (doc as any).lastAutoTable.finalY + 15;

    if (yPosition > 240) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Work Items Summary', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Tasks: ${totalTasks}`, margin + 5, yPosition);
    yPosition += 6;
    doc.text(`Total Milestones: ${totalMilestones}`, margin + 5, yPosition);
    yPosition += 6;
    doc.text(`Completed: ${completedItems}`, margin + 5, yPosition);
    yPosition += 6;
    doc.text(`Overdue: ${overdueItems}`, margin + 5, yPosition);
  }

  // Page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
};

