
'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Copy, Check, KeyRound } from 'lucide-react';
import { format, parseISO } from 'date-fns';
import { type License } from './LicenseGenerator';
import { useToast } from '@/hooks/use-toast';

interface LicenseListProps {
    licenses: License[];
}

export default function LicenseList({ licenses }: LicenseListProps) {
    const [copiedKey, setCopiedKey] = useState<string | null>(null);
    const { toast } = useToast();

    const copyToClipboard = (key: string) => {
        navigator.clipboard.writeText(key);
        setCopiedKey(key);
        toast({ title: "License key copied to clipboard." });
        setTimeout(() => setCopiedKey(null), 2000);
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle>Generated Licenses</CardTitle>
                <CardDescription>
                    A list of all license keys that have been generated by the system.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <div className="overflow-x-auto">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Purchaser</TableHead>
                                <TableHead>License Key</TableHead>
                                <TableHead className="text-center">Directors</TableHead>
                                <TableHead className="text-center">Admins</TableHead>
                                <TableHead className="text-center">Engineers</TableHead>
                                <TableHead>Expires At</TableHead>
                                <TableHead>Generated At</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {licenses.length > 0 ? (
                                [...licenses].reverse().map(license => (
                                    <TableRow key={license.key}>
                                        <TableCell className="font-medium">{license.purchaser}</TableCell>
                                        <TableCell>
                                            <div className="flex items-center gap-2">
                                                <KeyRound className="h-4 w-4 text-muted-foreground" />
                                                <span className="font-mono text-xs truncate max-w-xs">{license.key}</span>
                                                <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => copyToClipboard(license.key)}>
                                                    {copiedKey === license.key ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                                                </Button>
                                            </div>
                                        </TableCell>
                                        <TableCell className="text-center">{license.maxDirectors}</TableCell>
                                        <TableCell className="text-center">{license.maxAdmins}</TableCell>
                                        <TableCell className="text-center">{license.maxEngineers}</TableCell>
                                        <TableCell>
                                            {license.expiresAt === 'Unlimited' ? (
                                                <Badge variant="secondary">Unlimited</Badge>
                                            ) : (
                                                format(parseISO(license.expiresAt), 'PPP')
                                            )}
                                        </TableCell>
                                        <TableCell>{format(parseISO(license.createdAt), 'PPP p')}</TableCell>
                                    </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                    <TableCell colSpan={7} className="h-24 text-center">
                                        No licenses have been generated yet.
                                    </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </div>
            </CardContent>
        </Card>
    );
}
