
'use client';

import { usePathname } from 'next/navigation';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Printer, FileDown, FileSpreadsheet } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { useReportContext } from '@/contexts/ReportContext';
import { useAuth } from '@/hooks/use-auth';

export default function ReportsPageLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const isReportDetailsPage = pathname.includes('/engineer-summary') || pathname.includes('/engineer-performance') || pathname.includes('/detailed-claims') || pathname.includes('/project-status') || pathname.includes('/task-milestone-report');
  
  const context = useReportContext();
  const { user } = useAuth();

  const handlePrint = () => {
    window.print();
  };

  const handleExcelExport = () => {
    if (pathname.includes('/engineer-summary')) {
        context.exportSummaryToExcel();
    } else if (pathname.includes('/engineer-performance')) {
        context.exportPerformanceToExcel();
    } else if (pathname.includes('/detailed-claims')) {
        context.exportDetailedClaimsToExcel();
    } else if (pathname.includes('/project-status')) {
        context.exportProjectStatusToExcel();
    } else if (pathname.includes('/task-milestone-report')) {
        context.exportTaskMilestoneToExcel();
    }
  }

  const handleExportAll = () => {
    context.exportAllToExcel();
  }
  
  const getReportTitle = () => {
    if (pathname.includes('/engineer-summary')) {
      return "SitePilot - Engineer Summary Report";
    }
    if (pathname.includes('/engineer-performance')) {
      return "SitePilot - Engineer Performance Report";
    }
    if (pathname.includes('/detailed-claims')) {
        return "SitePilot - Detailed Claims Report";
    }
     if (pathname.includes('/project-status')) {
        return "SitePilot - Project Status Report";
    }
     if (pathname.includes('/task-milestone-report')) {
        return "SitePilot - Task &amp; Milestone Report";
    }
    return "SitePilot - All Reports";
  }

  return (
    <div className="print-container space-y-6">
      <div className="print-hidden flex flex-col items-stretch justify-between gap-4 sm:flex-row sm:items-center">
        {isReportDetailsPage ? (
          <Button variant="outline" asChild>
            <Link href="/dashboard/reports">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Reports Hub
            </Link>
          </Button>
        ) : (
          <div /> 
        )}
        
        <div className='flex gap-2'>
            <DropdownMenu>
                <DropdownMenuTrigger asChild>
                <Button className="w-full sm:w-auto">
                    <FileDown className="mr-2 h-4 w-4" />
                    Export
                </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                {isReportDetailsPage ? (
                    <>
                        <DropdownMenuItem onClick={handlePrint}>
                            <Printer className="mr-2 h-4 w-4" />
                            <span>Print to PDF</span>
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={handleExcelExport}>
                            <FileSpreadsheet className="mr-2 h-4 w-4" />
                            <span>Export to Excel</span>
                        </DropdownMenuItem>
                    </>
                ) : (
                    <>
                        <DropdownMenuItem onClick={handlePrint}>
                            <Printer className="mr-2 h-4 w-4" />
                            <span>Print All to PDF</span>
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={handleExportAll}>
                            <FileSpreadsheet className="mr-2 h-4 w-4" />
                            <span>Export All to Excel</span>
                        </DropdownMenuItem>
                    </>
                )}
                </DropdownMenuContent>
            </DropdownMenu>
        </div>
      </div>
      
      <div id="print-header" className="print-only hidden">
          <div className="flex justify-between items-end">
              <div>
                  <h1 className="text-2xl font-bold">{getReportTitle()}</h1>
                  <p className="text-muted-foreground">Generated on: {new Date().toLocaleDateString()}</p>
              </div>
              <p className="text-sm text-muted-foreground">
                  Generated by: {user?.name || 'N/A'}
              </p>
          </div>
          <div className="border-t mt-2 mb-6"></div>
      </div>


      {children}

      <div id="print-footer" className="print-only hidden">
          <div className="border-t mt-6 pt-2 text-sm text-muted-foreground">
             <div className="flex justify-between">
                <span>Page <span className="page-number"></span> of <span className="total-pages"></span></span>
                <span>Report generated by SitePilot</span>
             </div>
          </div>
      </div>
    </div>
  );
}
