
'use client';

import { usePathname } from 'next/navigation';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Printer, FileDown, FileSpreadsheet } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { useReportContext } from '@/contexts/ReportContext';
import { useAuth } from '@/hooks/use-auth';

export default function ReportsPageLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const isReportDetailsPage = pathname.includes('/engineer-summary');
  
  // Conditionally get the context to avoid errors on pages that don't need it.
  const context = isReportDetailsPage ? useReportContext() : null;
  const { user } = useAuth();

  const handlePrint = () => {
    window.print();
  };

  const handleExcelExport = () => {
    if (context) {
        context.exportToExcel();
    }
  }

  return (
    <div className="print-container space-y-6">
      <div className="print-hidden flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
        {isReportDetailsPage ? (
          <Button variant="outline" asChild>
            <Link href="/dashboard/reports">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Reports Hub
            </Link>
          </Button>
        ) : (
          <div /> // Placeholder to keep layout consistent
        )}
        
        {isReportDetailsPage && (
           <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button>
                <FileDown className="mr-2 h-4 w-4" />
                Export
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem onClick={handlePrint}>
                <Printer className="mr-2 h-4 w-4" />
                <span>Print to PDF</span>
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleExcelExport}>
                 <FileSpreadsheet className="mr-2 h-4 w-4" />
                <span>Export to Excel</span>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )}
      </div>
      
      <div id="print-header" className="print-only hidden">
          <div className="flex justify-between items-end">
              <div>
                  <h1 className="text-2xl font-bold">SitePilot - Engineer Summary Report</h1>
                  <p className="text-muted-foreground">Generated on: {new Date().toLocaleDateString()}</p>
              </div>
              <p className="text-sm text-muted-foreground">
                  Generated by: {user?.name || 'N/A'}
              </p>
          </div>
          <div className="border-t mt-2 mb-6"></div>
      </div>


      {children}

      <div id="print-footer" className="print-only hidden">
          <div className="border-t mt-6 pt-2 text-sm text-muted-foreground">
             <div className="flex justify-between">
                <span>Page <span className="page-number"></span> of <span className="total-pages"></span></span>
                <span>Report generated by SitePilot</span>
             </div>
          </div>
      </div>
    </div>
  );
}
